updates env var to NEW_SUBZONE_SIG0_KEY

diff --git a/register_key b/register_key
--- a/register_key
+++ b/register_key
@@ -8,7 +8,7 @@
 for i in functions/*.sh
 do
         . ${i}
-        [[ -n ${DEBUG} ]] && echo "Sourced ${PWD}/functions/$i ..."
+        [[ -n ${DEBUG_SOURCED} ]] && echo "Sourced ${PWD}/$i ..."
 done
 
 #------------------------------------------------------------------------------
@@ -46,17 +46,17 @@ fi
 
 
 # find any existing key from keystore
-# 	Note: NSUPDATE_SIG0_KEYID value updated by reference in get_sig0_keyid() 
-get_sig0_keyid NSUPDATE_SIG0_KEYID ${SIG0_KEY_FQDN} ${NSUPDATE_SIG0_KEYPATH}
+# 	Note: NEW_SUBZONE_SIG0_KEYID value updated by reference in get_sig0_keyid()
+get_sig0_keyid NEW_SUBZONE_SIG0_KEYID ${SIG0_KEY_FQDN} ${NSUPDATE_SIG0_KEYPATH}
 
 # if no such key exists in keystore, create a new keypair in keystore
-if [[ ! -n ${NSUPDATE_SIG0_KEYID} ]]; then
+if [[ ! -n ${NEW_SUBZONE_SIG0_KEYID} ]]; then
 	[[ -n ${DEBUG} ]] && echo "No SIG0 keypair for ${SIG0_KEY_FQDN} found in ${NSUPDATE_SIG0_KEYPATH}"
 	SIG0_KEY_ALGO=${SIG0_KEY_ALGO:-"ED25519"}
 	dnssec-keygen -K ${NSUPDATE_SIG0_KEYPATH} -a ${SIG0_KEY_ALGO} -n HOST -T KEY ${SIG0_KEY_FQDN}
 	echo "New SIG0 keypair for ${SIG0_KEY_FQDN} generated in ${NSUPDATE_SIG0_KEYPATH}"
-       	get_sig0_keyid NSUPDATE_SIG0_KEYID ${SIG0_KEY_FQDN} ${NSUPDATE_SIG0_KEYPATH}
-	[[ ! -n ${NSUPDATE_SIG0_KEYID} ]] && echo "Error creating new key for ${SIG0_KEY_FQDN} in keystore ${NSUPDATE_SIG0_KEYPATH}" && exit 1
+	get_sig0_keyid NEW_SUBZONE_SIG0_KEYID ${SIG0_KEY_FQDN} ${NSUPDATE_SIG0_KEYPATH}
+	[[ ! -n ${NEW_SUBZONE_SIG0_KEYID} ]] && echo "Error creating new key for ${SIG0_KEY_FQDN} in keystore ${NSUPDATE_SIG0_KEYPATH}" && exit 1
 fi
 
 #
@@ -68,9 +68,9 @@ UPDATE_TTL=${UPDATE_TTL:-"60"}
 
 NSUPDATE_ACTION=${NSUPDATE_ACTION:-"add"}
 
-NEW_SUBZONE_UPDATE_KEY="`cat ${NSUPDATE_SIG0_KEYPATH}/${NSUPDATE_SIG0_KEYID}.key`"
+NEW_SUBZONE_SIG0_KEY="`cat ${NSUPDATE_SIG0_KEYPATH}/${NEW_SUBZONE_SIG0_KEYID}.key`"
 # create item for *request* with KEY RR under ${SIGNAL_SUBZONE}.${ZONE}
-NSUPDATE_ITEM_SIG0_KEY="update ${NSUPDATE_ACTION} ${NEW_SUBZONE}.${SIGNAL_SUBZONE}.${ZONE} ${UPDATE_TTL} ${NEW_SUBZONE_UPDATE_KEY##*.}"
+NSUPDATE_ITEM_SIG0_KEY="update ${NSUPDATE_ACTION} ${NEW_SUBZONE}.${SIGNAL_SUBZONE}.${ZONE} ${UPDATE_TTL} ${NEW_SUBZONE_SIG0_KEY##*.}"
 
 # create pointer RR for processing list
 NSUPDATE_ITEM_PTR="update ${NSUPDATE_ACTION} ${SIGNAL_SUBZONE}.${ZONE} ${UPDATE_TTL} PTR ${NEW_SUBZONE}.${SIGNAL_SUBZONE}.${ZONE}."
@@ -82,8 +82,8 @@ if [[ -n ${DEBUG} ]]; then
 	echo
 	echo "SUBZONE KEY Request FQDN  =	${NEW_SUBZONE}.${SIGNAL_SUBZONE}.${ZONE}"
 	echo "  Requested SIG0 KEY FQDN            =	${SIG0_KEY_FQDN}"
-	echo "  Requested SIG0 DNS Update KEY ID   =	${NSUPDATE_SIG0_KEYID}"
-	echo "  Requested SIG0 DNS Update KEY file =	${NEW_SUBZONE_UPDATE_KEY}"
+	echo "  Requested SIG0 DNS Update KEY ID   =	${NEW_SUBZONE_SIG0_KEYID}"
+	echo "  Requested SIG0 DNS Update KEY file =	${NEW_SUBZONE_SIG0_KEY}"
 fi
 
 if [[ -n ${DEBUG} ]]; then
